#pragma once
#ifndef RAPIDJSON_HAS_STDSTRING
#define RAPIDJSON_HAS_STDSTRING 1
#endif
#include <memory>
#include <rapidjson/document.h>
#include <string>
#include <vector>
#include "AdoCpp/Utils.h"

namespace AdoCpp::Event
{
    /**
     * @brief Event class.
     */
    class Event
    {
    public:
        /**
         * @brief Default constructor.
         */
        Event() = default;
        /**
         * @brief Default destructor.
         */
        virtual ~Event() = default;
        /**
         * @brief Convert json data into Event class.
         * @param data Json data.
         */
        explicit Event(const rapidjson::Value& data);
        /**
         * @brief Floor of event.
         */
        size_t floor = 0;
        /**
         * @brief Represent whether event is active.
         */
        bool active = true;
        /**
         * @brief Get whether event is stackable.
         * @return Whether event is stackable.
         */
        [[nodiscard]] constexpr virtual bool stackable() const noexcept = 0;
        /**
         * @brief Get name of event.
         * @return Name of event.
         */
        [[nodiscard]] constexpr virtual const char* name() const noexcept = 0;
        /**
         * @brief Clone the event.
         *
         * The method is used in order to make cloning events easier.
         *
         * For example, RepeatEvents use the method
         * so that it does not need to figure out the type of the event.
         * @return The cloned event.
         */
        [[nodiscard]] constexpr virtual Event* clone() const = 0;
        /**
         * @brief Convert event into json value data.
         * @param alloc Allocator.
         * @return Unique pointer of json value data.
         */
        [[nodiscard]] virtual std::unique_ptr<rapidjson::Value>
        intoJson(rapidjson::Document::AllocatorType& alloc) const = 0;
        /**
         * @brief Convert event into json document data.
         * @return Unique pointer of json document data.
         */
        [[nodiscard]] std::unique_ptr<rapidjson::Document> intoJson() const;
    };

    /**
     * @brief StaticEvent class.
     */
    class StaticEvent : public Event
    {
    public:
        /**
         * @brief Default constructor.
         */
        StaticEvent() = default;
        /**
         * @brief Default destructor
         */
        ~StaticEvent() override = default;
        /**
         * @brief Convert json data into StaticEvent class.
         * @param data Json data.
         */
        explicit StaticEvent(const rapidjson::Value& data);
    };

    /**
     * @brief DynamicEvent class.
     */
    class DynamicEvent : public Event
    {
    public:
        /**
         * @brief Default constructor.
         */
        DynamicEvent() = default;
        /**
         * @brief Default destructor.
         */
        ~DynamicEvent() override = default;
        /**
         * Convert json data into DynamicEvent class.
         * @param data The json data.
         */
        explicit DynamicEvent(const rapidjson::Value& data);
        /**
         * @brief Clone the event.
         * @return the cloned event.
         * @see AdoCpp::Event::clone
         */
        [[nodiscard]] constexpr DynamicEvent* clone() const override = 0;
        /**
         * @brief Angle offset of event.
         */
        double angleOffset = 0;
        /**
         * @brief Beat of event.
         */
        double beat = 0;
        /**
         * @brief Seconds of event.
         */
        double seconds = 0;
        /**
         * @brief Tags of event.
         */
        std::vector<std::string> eventTag;
        /**
         * @brief Whether the event is not written in level data but generated by AdoCpp.
         */
        bool generated = false;
    };
} // namespace AdoCpp::Event
